# v3 syntax
version: '3'

networks:
  host:
    driver: bridge

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: app-mysql
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - host
    ports:
      - "3306:3306"
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test  

  # PHPMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: app-pma
    networks:
      - host
    ports:
      - 8081:80
    environment:
      TZ: America/Sao_Paulo
      PMA_HOST: mysql
      PMA_PORT: 3306
